#first we print the list of students
puts "The students of my cohort at Makers Academy"
puts "------------------"
puts "Ed B"
puts "Ben H"
puts "Rich L"
puts "Chris H"
puts "Victoria S"
puts "Ella S"
puts "Izzy M"
puts "Nick D"
puts "Alex B"
puts "Giorgia A"
puts "Chris B"
puts "Dale S"
puts "Alan B"
puts "Tim S"
puts "Mishal I"
puts "Pavel R"
puts "Simon L"
puts "Clare T"
puts "Claudia B"
puts "Ben C"
#finally, we print the total
print "Overall, we have "
#It's important that print() doesn't adde new line characters
print 20
puts " great students"
